# hydra config
hydra:
  run:
    dir: /workspace/code/logs/prepare_dataset/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false

YOLO:
  pose_ckpt: "/workspace/code/ckpt/yolov8x-pose.pt"
  seg_ckpt: "/workspace/code/ckpt/yolov8x-seg.pt"
  bbox_ckpt: "/workspace/code/ckpt/yolov8x.pt"
  conf: 0.8
  iou: 0.5
  verbose: False
  device: 0

# Path
# step1: from raw video to extract video.
# use YOLOv8 detection with tracking.
extract_dataset:
  data_path: "" # this is raw data path.
  save_path: "/workspace/data/segmentation_dataset_512" # this is extracted video path.

# step2: from extracted video to define the gait cycle.
gait_dataset:
  data_path: "/workspace/data/segmentation_dataset_512" # meta four view dataset path, with human annotation.
  save_path: "/workspace/data/multi_cue_dataset" # convert the four view dataset into a format of the annotation file.

log_path: "${gait_dataset.save_path}/logs/"
task: ["pose", "mask", "bbox", "depth", "optical_flow"]
